# ===============================
# Dockerfile.streamlit : Image pour Streamlit
# ===============================

FROM python:3.11-slim

WORKDIR /app

# Installer uv
RUN pip install --no-cache-dir uv

# Copier et installer les dépendances
COPY requirements.txt ./
RUN uv pip install -r requirements.txt

# Copier tout le code source
COPY . .

# Exposer le port Streamlit
EXPOSE 8501

# Commande de lancement (Streamlit)
CMD ["streamlit", "run", "src/app/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
