services:
  - type: web
    name: assurance-pricing-api
    runtime: docker
    plan: free
    dockerfilePath: prod_api_rest/app/api/Dockerfile
    healthCheckPath: /v1/health
    envVars:
      - key: PORT
        value: 8000
